apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  labels:
    app: shoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: akstestkvk.azurecr.io/shoppingclient:1200
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: shoppingapi-configmap
                    key: shoppingapi_url
          resources:
            requests:
              memory: "256Mi"
              cpu: "1000m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 80           